# -*- coding: utf-8 -*-
# Copyright 2026 Weha
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0).

from odoo import api, fields, models
import logging

_logger = logging.getLogger(__name__)


class StockRequest(models.Model):
    """Extend Stock Request to link replenishment rules"""
    _inherit = 'stock.request'
    
    replenishment_rule_id = fields.Many2one(
        'stock.replenishment.rule',
        string='Replenishment Rule',
        readonly=True,
        help='Replenishment rule that triggered this request'
    )
    is_auto_generated = fields.Boolean(
        string='Auto Generated',
        default=False,
        readonly=True,
        help='This request was automatically generated by replenishment rule'
    )
    
    def _prepare_stock_move(self, qty):
        """
        Override to ensure destination location is always the requester's location.
        
        Simple rule: 
        - location_dest_id = self.location_id (where the requester wants the stock)
        - location_id = will be determined by route or source location
        """
        vals = super()._prepare_stock_move(qty)
        
        # FORCE destination to be the stock request's location (requester's location)
        vals['location_dest_id'] = self.location_id.id
        
        # Try to get source location from route if available
        if self.route_id:
            rules = self.route_id.rule_ids.filtered(
                lambda r: r.location_dest_id == self.location_id and r.action == 'pull'
            )
            if rules:
                vals['location_id'] = rules[0].location_src_id.id
            elif self.replenishment_rule_id and self.replenishment_rule_id.source_ou_id:
                # Fallback: get source from source OU's warehouse
                warehouse = self.env['stock.warehouse'].search([
                    ('operating_unit_id', '=', self.replenishment_rule_id.source_ou_id.id)
                ], limit=1)
                if warehouse and warehouse.lot_stock_id:
                    vals['location_id'] = warehouse.lot_stock_id.id
        
        return vals
    
    @api.model_create_multi
    def create(self, vals_list):
        """Override create to ensure location_id and operating_unit_id are set correctly"""
        # Ensure operating_unit_id is set if creating from replenishment rule
        for vals in vals_list:
            if vals.get('replenishment_rule_id') and not vals.get('operating_unit_id'):
                rule = self.env['stock.replenishment.rule'].browse(vals['replenishment_rule_id'])
                vals['operating_unit_id'] = rule.operating_unit_id.id
        
        records = super().create(vals_list)
        
        # After creation, ensure any created moves have correct destination AND operating unit
        for record in records:
            if record.move_ids:
                move_vals = {
                    'location_dest_id': record.location_id.id,
                }
                # Ensure operating unit is set
                if record.operating_unit_id:
                    # Note: We can't set operating_unit_id and operating_unit_dest_id directly
                    # as they are related fields. The constraint will pass if destination location
                    # belongs to the requesting OU
                    pass
                record.move_ids.write(move_vals)
        
        return records
    
    def _action_confirm(self):
        """Override confirm to fix move locations and ensure proper OU setup"""
        res = super()._action_confirm()
        
        # After confirmation, ensure all moves and pickings have correct setup
        for request in self:
            _logger.info('Stock Request %s: OU=%s, Warehouse=%s, Location=%s',
                        request.name,
                        request.operating_unit_id.name if request.operating_unit_id else 'None',
                        request.warehouse_id.name if request.warehouse_id else 'None',
                        request.location_id.complete_name if request.location_id else 'None')
            
            # Ensure pickings have correct operating unit
            if request.picking_ids and request.operating_unit_id:
                for picking in request.picking_ids:
                    if not picking.operating_unit_id or picking.operating_unit_id != request.operating_unit_id:
                        _logger.warning('Fixing picking %s OU from %s to %s',
                                       picking.name,
                                       picking.operating_unit_id.name if picking.operating_unit_id else 'None',
                                       request.operating_unit_id.name)
                        # Try to update the picking's OU
                        # Note: This might fail if picking_type doesn't match
                        try:
                            picking.write({'operating_unit_id': request.operating_unit_id.id})
                        except Exception as e:
                            _logger.error('Failed to set picking OU: %s', str(e))
            
            if request.move_ids:
                for move in request.move_ids.filtered(lambda m: m.state not in ['done', 'cancel']):
                    _logger.info('  Move %s: Picking OU=%s, Source=%s (OU=%s), Dest=%s (OU=%s)',
                                move.reference,
                                move.picking_id.operating_unit_id.name if move.picking_id and move.picking_id.operating_unit_id else 'None',
                                move.location_id.complete_name,
                                move.location_id.operating_unit_id.name if move.location_id.operating_unit_id else 'None',
                                move.location_dest_id.complete_name,
                                move.location_dest_id.operating_unit_id.name if move.location_dest_id.operating_unit_id else 'None')
                    
                    # Force correct destination
                    move.write({'location_dest_id': request.location_id.id})
        
        return res
    
    def _prepare_procurement_values(self, group_id=False):
        """Override to ensure route from replenishment rule is used"""
        vals = super()._prepare_procurement_values(group_id=group_id)
        
        # Ensure route from replenishment rule is used
        if self.replenishment_rule_id and self.replenishment_rule_id.route_id:
            vals['route_ids'] = self.replenishment_rule_id.route_id
        
        # CRITICAL: Ensure warehouse_id is the DESTINATION warehouse (Store)
        # This determines the picking's operating_unit_id
        if self.warehouse_id:
            vals['warehouse_id'] = self.warehouse_id
            
        _logger.info('Procurement values for %s: warehouse=%s, route=%s',
                    self.name,
                    self.warehouse_id.name if self.warehouse_id else 'None',
                    self.replenishment_rule_id.route_id.name if self.replenishment_rule_id and self.replenishment_rule_id.route_id else 'None')
            
        return vals
    
    def _prepare_procurement_group_values(self):
        """Override to ensure operating unit is set on procurement group"""
        res = super()._prepare_procurement_group_values()
        
        # Ensure the procurement group has the correct operating unit (Store)
        if self.operating_unit_id:
            res['operating_unit_id'] = self.operating_unit_id.id
            _logger.info('Procurement group for %s: OU=%s', self.name, self.operating_unit_id.name)
            
        return res
